# Generated by Django 5.1.4 on 2024-12-07 01:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ANT', 'Antibiotic'), ('ANA', 'Anesthesia'), ('ANTH', 'AntiHistamine'), ('ANL', 'Analgesic'), ('ANT', 'Antiviral'), ('CAR', 'Cardiac'), ('OTH', 'Other')], default='OTH', max_length=4)),
                ('descriptionType', models.TextField(verbose_name='Description')),
                ('in_Stock', models.IntegerField(default=0, verbose_name='In Stock')),
                ('minimum_stock', models.IntegerField(default=10, verbose_name='Minimum Stock Level')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_Date', models.DateField(verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Drugs',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['barcode'], name='app_drug_barcode_e93794_idx'), models.Index(fields=['name'], name='app_drug_name_4ca369_idx'), models.Index(fields=['category'], name='app_drug_categor_bbaa33_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Invoice Date')),
                ('product_Description', models.TextField(verbose_name='Product Description')),
                ('quantity', models.IntegerField()),
                ('unit_Price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.drug')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['invoice_date'], name='app_invoice_invoice_4c5ec2_idx'), models.Index(fields=['payment_status'], name='app_invoice_payment_34eb73_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_changed', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='app.drug')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='app_stockmo_date_377ca4_idx'), models.Index(fields=['movement_type'], name='app_stockmo_movemen_0c11dc_idx')],
            },
        ),
    ]
