# Generated by Django 5.1.4 on 2024-12-07 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='app_invoice_invoice_4c5ec2_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='app_invoice_payment_34eb73_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product_Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unit_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
