# Generated by Django 5.1.4 on 2024-12-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_invoice_app_invoice_invoice_4c5ec2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum stock level before reordering', max_digits=10),
        ),
    ]
